from __future__ import annotations

import threading
from typing import Any, Protocol

from core.models import AxisCal, AxisComm, Recipe


class LengthHostProtocol(Protocol):
    axis_cal: AxisCal
    recipe: Recipe

    def get_axis_copy(self, axis: int) -> AxisComm: ...
    def movea_abs(self, axis: int, pos_abs: float, *, context: str = "MoveA") -> None: ...
    def _recipe_ui_widget(self, name: str) -> Any: ...
    def _ui_set(self, var: Any, value: str) -> None: ...
    def _ui_btn_text(self, btn: Any, text: str) -> None: ...
    def _velmove_start_axis(
        self,
        axis: int,
        vel_velmove: float,
        *,
        acc: float = 80.0,
        dec: float = 80.0,
        jerk: float = 300.0,
    ) -> None: ...
    def _velmove_stop_axis(self, axis: int) -> None: ...
    def _wait_axis_stop_settled(
        self,
        axis: int,
        *,
        timeout_s: float = 1.5,
        stable_cycles: int = 8,
        eps_abs: float = 0.02,
        stop_evt: threading.Event | None = None,
    ) -> bool: ...
    def after(self, ms: Any, func: Any | None = None, *args: Any) -> Any: ...


class TeachHostProtocol(Protocol):
    axis_cal: AxisCal
    recipe: Recipe

    def _recipe_ui_widget(self, name: str) -> Any: ...
    def _recipe_apply_from_ui(self) -> Recipe: ...
    def _get_selected_recipe_idx(self) -> int | None: ...
    def _ensure_recipe_section_plan(self, recipe: Recipe | None = None) -> Any: ...
    def _save_taught_section_to_recipe(self, recipe: Recipe, recipe_index: int, z_od_disp: float) -> None: ...
    def _refresh_recipe_table(self) -> None: ...
    def _refresh_length_info(self) -> None: ...
    def get_axis_copy(self, axis: int) -> AxisComm: ...
    def movea_abs(self, axis: int, pos_abs: float, *, context: str = "MoveA") -> None: ...
    def apply_soft_limits_abs(self, axis: int, target_abs: float, *, strict: bool = False, context: str = "") -> float: ...
    def _write_axis_params(self, axis: int) -> None: ...
    def set_cmd_bits(self, axis: int, set_mask: int = 0, clr_mask: int = 0) -> None: ...
    def after(self, ms: Any, func: Any | None = None, *args: Any) -> Any: ...
